// <auto-generated />
namespace MarsRoverChallengeWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20150521 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150521));
        
        string IMigrationMetadata.Id
        {
            get { return "201505211118503_20150521"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
